<?php
/** @var Pay_Payment_Model_Paymentmethod $this */
$_code = $this->getMethodCode();
$dob = $this->getDob();

list($dobYear,$dobMonth,$dobDay) = explode('-',$dob);

?>


<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>Geboortedatum</li>
    <li>
        <div class="input-box customer-dob">
            <div class="dob-day">
                <input type="text" id="day" name="payment[birthday_day]" value="<?php echo $dobDay; ?>" title="Day"
                       class="input-text">
                <label for="day">DD</label>
            </div>
            <div class="dob-month">
                <input type="text" id="month" name="payment[birthday_month]" value="<?php echo $dobMonth; ?>" title="Month"
                       class="input-text">
                <label for="month">MM</label>
            </div>
            <div class="dob-year">
                <input type="text" id="year" name="payment[birthday_year]" value="<?php echo $dobYear; ?>" title="Year"
                       class="input-text" autocomplete="off">
                <label for="year">YYYY</label>
            </div>
    </li>
    <li>IBAN</li>
    <li>
        <input type="text" id="iban" name="payment[iban]" value="<?php echo $this->getIban(); ?>" title="iban" class="input-text" placeholder="iban">
    </li>

</ul>
<div>
    <?php echo $this->getMethod()->getConfigData('message'); ?>
</div>
