<?php
$_code = $this->getMethodCode();
?>
<ul id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li><strong>Let op! Er wordt geen email verstuurd, de betaallink vind je in de notities bij de order</strong></li>
    <li>
        <div class="input-box">


            <label for="valid_days">Geldigheid in dagen</label><br>
            <select id="valid_days" name='payment[valid_days]'>
                <?php for ($i = 1; $i < 31; $i++) {
                    $selected = '';
                    if ($i == 7) $selected = "selected=''";
                    echo "<option value='$i' $selected >$i</option>";
                } ?>
            </select>
        </div>
    </li>


</ul>
<div>
    <?php echo $this->getMethod()->getConfigData('message'); ?>
</div>
