<?php 
    $_code=$this->getMethodCode();
    
    $banks = $this->getBanks();
?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li><?php echo Mage::getStoreConfig('payment/'.$_code.'/text_bankselect', Mage::app()->getStore()); ?></li>
    <?php
    foreach($banks as $bank){
        echo "<li><input id='".$_code."_".$bank->getOptionSubId()."' type='radio' name='payment[option_sub]' value='".$bank->getOptionSubId()."' class='radio' />"
                . "<label style='float:none;' for='".$_code."_".$bank->getOptionSubId()."'> <img title='".$bank->getName()."' src='".$bank->getImage()."' /></label></li>";
    }
    ?>
</ul>
<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>
